---
- name: Generate and install self-signed SSL certificate for Nginx
  hosts: webserver
  become: yes

  vars:
    domain: "homelab.lan"

  tasks:
    - name: Get the hostname of the server
      setup:
        filter: ansible_hostname
      register: hostname

    - name: Set the hostname as domain_name
      set_fact:
        domain_name: "{{ hostname.ansible_facts.ansible_hostname }}.{{ domain }}"

    - name: Check the SSL certificate validity
      set_fact:
        current_time: "{{ ansible_date_time.epoch | int }}"

    - name: Get the SSL certificate expiry time
      command: "openssl x509 -enddate -noout -in /etc/ssl/certs/{{ domain_name }}.crt | cut -d'=' -f2-"
      register: cert_end_date

    - name: Calculate the Unix timestamp for SSL certificate expiry
      set_fact:
        cert_expiry_time: "{{ cert_end_date.stdout | trim | to_datetime('%b %d %H:%M:%S %Y %Z') | to_unixtime }}"

    - name: Renew SSL certificate if it's expiring soon
      command: "openssl req -x509 -newkey rsa:4096 -keyout /etc/ssl/private/{{ domain_name }}.key -out /etc/ssl/certs/{{ domain_name }}.crt -days 365 -nodes -subj '/CN={{ domain_name }}'"
      when: cert_expiry_time | int < current_time + (2 * 7 * 24 * 3600)  # Renew if less than 2 weeks left
      register: cert_renew_result
      changed_when: cert_renew_result.stdout.find('not creating new certificate') == -1

    - name: Configure Nginx to use the updated SSL certificate
      blockinfile:
        path: "/etc/nginx/sites-available/default"  # Path to nginx-Config
        block: |
          server {
              listen 443 ssl;
              server_name {{ domain_name }};

              ssl_certificate /etc/ssl/certs/{{ domain_name }}.crt;
              ssl_certificate_key /etc/ssl/private/{{ domain_name }}.key;

              # ... Weitere SSL- und Serverkonfigurationen ...
          }
      when: cert_renew_result.changed

    - name: Reload Nginx to apply the SSL configuration
      systemd:
        name: "nginx"  # service name for nginx-service
        state: restarted
      when: cert_renew_result.changed
