---
- name: Update packages on Ubuntu
  hosts: ubuntu
  become: true  # Run tasks with sudo or equivalent on Linux
  
  tasks:
    - name: Update Ubuntu packages
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == 'Debian'  # This task will only run on Debian-based systems (like Ubuntu)
      
- name: Update packages on Windows
  hosts: windows
    - name: Update Windows packages
      win_updates:
        category_names:
          - SecurityUpdates
          - UpdateRollups
          - CriticalUpdates
        state: installed
      when: ansible_os_family == 'Windows'  # This task will only run on Windows systems
