---
- name: Show version of linux server
  hosts: all
  gather_facts: yes

  tasks:
    - name: search os version
      command: lsb_release -d
      register: version_output
      when: ansible_os_family == 'Debian'

    - name: print current os version
      debug:
      msg: "Current os version: {{ version_output.stdout }}"
