- name: Get SSL certificate expiry date in CEST
  hosts: webserver
  become: yes

  vars:
    domain: "homelab.lan"

  tasks:
    - name: Get the hostname of the server
      setup:
        filter: ansible_hostname
      register: hostname

    - name: Set the hostname as domain_name
      set_fact:
        domain_name: "{{ hostname.ansible_facts.ansible_hostname }}.{{ domain }}"

    - name: Check the SSL certificate validity
      command: "openssl x509 -enddate -noout -in /etc/ssl/certs/{{ domain_name }}.crt"
      register: cert_end_date

    - name: Get SSL certificate expiry date in UTC
      set_fact:
        cert_expiry_date_utc: "{{ (cert_end_date.stdout | trim | regex_replace('(notAfter=)','') | to_datetime('%b %d %H:%M:%S %Y %Z')).strftime('%Y-%m-%d %H:%M:%S') }}"

    - name: Get SSL certificate expiry date in CEST
      shell: "date -d '{{ cert_expiry_date_utc }}' +'%Y-%m-%d %H:%M:%S' --utc --date='TZ=\"Europe/Berlin\" {{ cert_expiry_date_utc }}'"
      register: cert_expiry_date_cest

    - name: Display SSL certificate expiry date in CEST
      debug:
        msg: "SSL certificate for {{ domain_name }} expires on {{ cert_expiry_date_cest.stdout }}"
